fix

diff --git a/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2 b/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2
--- a/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2
+++ b/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2
@@ -2,14 +2,14 @@
 
 
 ################################################################################
-### Head: Url
+### Head: Link
 ##
 
 # * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl
-# * https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/
+# * https://github.com/samwhelp/play-ubuntu-20.04-plan/blob/master/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2
 
 ##
-### Tail: Url
+### Tail: Link
 ################################################################################
 
 
@@ -17,16 +17,7 @@
 ### Head: Note
 ##
 
-# $ xfconf-query -c 'xsettings' -l | grep Theme
-#
-# /Gtk/CursorThemeName
-# /Gtk/CursorThemeSize
-# /Gtk/KeyThemeName
-# /Net/FallbackIconTheme
-# /Net/IconThemeName
-# /Net/SoundThemeName
-# /Net/ThemeName
-
+##
 
 ##
 ### Tail: Note
@@ -36,7 +27,7 @@
 ################################################################################
 ### Head: Init
 ##
-#set -e ## for Exit immediately if a command exits with a non-zero status.
+##set -e ## for Exit immediately if a command exits with a non-zero status.
 THE_BASE_DIR_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
 THE_CMD_FILE_NAME=$(basename $0)
 ##
@@ -96,13 +87,13 @@ base_var_init () {
 	THE_CMD_DIR_PATH="${THE_BASE_DIR_PATH}"
 
 	if [ "none${THE_CMD_FILE_NAME}" = 'none' ]; then
-		THE_CMD_FILE_NAME="style-ctrl-xfce"
+		THE_CMD_FILE_NAME="ob-tint2"
 	fi
 
 	THE_CMD_FILE_PATH="${THE_CMD_DIR_PATH}/$THE_CMD_FILE_NAME"
 
-	## https://github.com/samwhelp/play-ubuntu-20.04-plan/blob/master/project/style-xfce/style-ctrl/style-ctrl-xfce
-	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/play-ubuntu-20.04-plan/master/project/style-xfce/style-ctrl/style-ctrl-xfce'
+	## https://github.com/samwhelp/play-ubuntu-20.04-plan/blob/master/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2
+	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/play-ubuntu-20.04-plan/master/prototype-experiment/openbox-enhance/config/tint2/bin/ob-tint2'
 
 
 	THE_TMP_DIR_PATH="/tmp"
@@ -435,8 +426,6 @@ sub_run_version () {
 }
 
 sub_run_self_update () {
-	echo 'Todo:'
-	return
 	util_self_update
 }
 
